### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mateusjatenee** [mateusjatenee/tracker#1]
Although we don't have a proper roadmap document yet, we can track all of the pending features here, and assign people working on them (and a related PR) to keep track of things.  

# Exchange Module

## Asset
- [x] Initial models and [Lucidchart](https://lucid.app/lucidchart/51fe9315-893a-45c5-9e59-a3eaa2e14b75/edit?viewport_loc=-1916%2C11%2C4545%2C2007%2C0_0&invitationId=inv_289cc0d4-0cb5-4f73-a59e-474dc08b4ef6)
- [x] Ingest crypto coins prices automatically 
- [x] Add (at least one) `CryptoAssetInformationProvider`: Coinbase
- [ ] Add a seeder to load all existing crypto coins and stocks
- [ ] Ingest stock prices automatically 
- [ ] Add a stock price provider

## Portfolio
- [ ] Set up initials models: `Account`, `Transaction`, `Position`
- [ ] Calculate a given position on an asset based on the transactions on that asset

### Connection to exchanges
- [ ] import transactions from NASDAQ
- [ ] import transactions from IBOVESPA
- [ ] import transactions from Coinbase
- [ ] import transactions from Binance
- [ ] Automatically recalculate positions after importing transactions

## UI
TBD...

**Comment by mateusjatenee** [comment]
Figuring out portfolio stuff here https://github.com/mateusjatenee/tracker/pull/2
